version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - BOT_TOKEN=7434551862:AAFlu500u1D9D0yEu7YAOkno5JHETf4qpZ0
      - DATABASE_URL=postgresql://postgres:Admin2025@db:5432/telegram_bot
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_bot
    ports:
      - "5432:5432"

